### ISSUE TITLE
Architecture Diagrams and Writeups

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#1]
## Issue Description

Epic for handling areas of documentation for Cerana:
- [ ] #2 Create diagram and writeup for tasks and task-coordinator (agent replacement) 
- [ ] #3 Create diagram and writeup for network stack
- [ ] #4  Create writeup for security changes/requirements
- [ ] #5  Create diagram and writeup for single node component interaction
- [ ] #6  Create diagram and writeup for node-coordinator-controller 3 layer interaction
- [ ] #7  Create diagram and writeup for coordinator layer
- [ ] #8  Create writeup for dhcp architecture
- [ ] #9  Create writeup and flow diagram for boot process
- [ ] #10  Create flow-diagram and writeup for storage (zfs)
- [ ] #11 Create flow-diagram and writeup for process management
- [ ] #12  Create diagram and writeup for log management
- [ ] #13  Create writeup and flow-diagram for bootstrapping
- [ ] #14  Create writeup for key-value store
- [ ] #15  Create diagram and writeup for image service
