### ISSUE TITLE
Move Go Services to Travis

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#16]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Tue Feb 16 19:16:50 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/16_

---

Move all Go services to Travis.  I think that's about it.  Possibility that this may need to be an epic with each Go service as a separate card but I leave that to smarter people to determine.
- [x] mistifyio/mistify-agent-image#41
- [x] mistifyio/mistify-agent-libvirt#23
- [x] mistifyio/go-zfs#38
- [x] mistifyio/gozfs#18
- [x] mistifyio/lochness#123
- [x] mistifyio/mistify-agent#52
- [x] mistifyio/mistify-agent-docker#20
- [x] mistifyio/mistify-image-service#12

**Comment by pjnorton** [comment]
<a href="https://github.com/joshie"><img src="https://avatars.githubusercontent.com/u/1170912?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joshie](https://github.com/joshie)**
_Tue Feb 16 20:21:16 2016_

---

Let's create issues in the repositories for go products we care about and link them here.
