### ISSUE TITLE
[CLOSED] Create a proof of concept of the new coordinator-provider setup

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#18]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Thu Feb 18 21:49:05 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/18_

---
# ISSUES CONTAINED IN THIS EPIC
- [ ] mistifyio/coordinator#6 Add Tests to Coordinator
- [ ] mistifyio/coordinator#7 Create Basic Coordinator
- [ ] mistifyio/coordinator#8 Coordinator README
- [ ] mistifyio/acomm#9 Acomm Request Timeouts
- [ ] mistifyio/acomm#10 RawMessage for Acomm Request Args and Response Result
- [ ] mistifyio/acomm#11 Acomm README
- [ ] mistifyio/provider#7 Create a Basic Provider
- [ ] mistifyio/provider#8 Provider README
- [ ] mistifyio/provider#9 General Provider Package
- [ ] mistifyio/provider#10 Add Streaming Provider Support
- [ ] mistifyio/provider#11 Add Tests to Provider
- [ ] #21 Integrate Coordinator and Provider
- [ ] #24 Asynch Communication POC
# EPIC DESCRIPTION

Based on this document: https://docs.google.com/document/d/19hYu7ZbUQWMTCqviu2BIKhDN7mweiSEjC0alDRScRsM/edit
The current hypervisor setup, with a main agent and several somewhat tightly integrated subagents, is far from ideal. Complicated and limited action "pipelines" handling (dependent steps), static config file, subagents far less pluggable and swappable than hoped, brittle or nonexistent recovery/rollback. We are looking to replace this with a simpler and far more flexible setup that can be built upon. Until we think of a better name, we will call this coordinator-provider.
The coordinator is the equivalent to the agent, but a lot simpler. It will accept incoming JSON-RPC requests, route the request to the appropriate provider based on the request task, and return the final result. Providers will "register" with the coordinator with what tasks they provide handlers for. Possibly something as simple as creating UNIX sockets in a defined way that the coordinator can access, keeping both registration and de-registration dead simple. Consider a prioritization system to help if multiple providers can handle the same task.
The providers handle the actual tasks. If there are any required subtasks to run before or after, the provider will make appropriate JSON-RPC requests to the coordinator, even if the same provider can handle it. This keeps control and decision making with the coordinator, allowing for more modularity.
Tasks should be broken down into simple building blocks. It becomes easier to plug things in and replace components. Tasks should all have an equivalent Rollback task if they make any modifications.
An example to illustrate:
Consider a situation with user `User`, coordinator `coordinator`, provider `Foo`, and provider `Bar`.
- Foo`provides`SystemReport`,`GetCPU`,`GetMem`, and`GetDisk` all at priority 50.
- Bar`provides`GetDisk` at priority 60.
1. `User` makes a request to `Coordinator` for `SystemReport`
2. Coordinator`finds that`Foo`provides`SystemReport`and passes the request to Foo`
3. `Foo''s handler of`SystemReport`aggregates the results of several subtasks.`Foo`makes requests to`Coordinator`for`GetCPU`,`GetMem`, and`GetDisk`
4. `Coordinator` handles the new requests.
   1. `Coordinator` finds that `Foo` provides `GetCPU`, routes the request to `Foo` and response back to `Foo`
   2. `Coordinator` finds that `Foo` provides `GetMem`, routes the request to `Foo` and the response back to `Foo`
   3. `Coordinator` finds that both `Foo` and `Bar` provide `GetDisk`. Since `Bar` is higher priority, the request is routed to `Bar` and the response back to `Foo`
5. `Foo` aggregates the responses and returns to `Coordinator`
6. `Coordinator` returns to `User`

**Comment by pjnorton** [comment]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pjnorton](https://github.com/pjnorton)**
_Thu Feb 18 21:50:36 2016_

---

Discussion with Josh and Manny today on the communication:
Everything will be async and it is up to the caller to decide how it wants to handle things.
Requesters will provide an id, "webhook" location, and the arguments.
Providers will respond immediately (either "ok" or some error if parameters are missing, etc.)
Providers then do work and send the id and real response to the webhook location from the request.
Some method of keeping track of these requests and responses will be needed, but shouldn't be terribly complicated. It should be able to handle both unix sockets and http.
